#!/usr/bin/env python3
"""Generate _colors_generated.css and _colors_generated.js from btc_web/colors.py.

Usage:
    python tools/generate_color_artifacts.py            # write artifacts
    python tools/generate_color_artifacts.py --check    # exit 1 if drift
"""
from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

# Ensure btc_web is on the path so we can `import colors`
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_PROJECT_ROOT / "btc_web"))
sys.path.insert(0, str(_PROJECT_ROOT))

import colors  # noqa: E402

CSS_PATH = _PROJECT_ROOT / "btc_web" / "assets" / "_colors_generated.css"
JS_PATH  = _PROJECT_ROOT / "btc_web" / "assets" / "_colors_generated.js"

# Names from colors.py that the generator should NOT emit.
SKIP = getattr(colors, "__skip_export__", frozenset())


def _kebab(name: str) -> str:
    """snake_case → kebab-case."""
    return name.replace("_", "-").lower()


def _flatten_palette_for_css(palette: dict, prefix: str = "qs") -> list[tuple[str, str]]:
    """Flatten one palette dict into a list of (--qs-...-key, hex) entries.

    Returns CSS variable name and value pairs for everything except
    `thermal_stops` (a list of (float, str) tuples — exposed only as
    JS arrays, NOT as individual CSS vars, since the float quantile
    values aren't meaningful selector keys). The isinstance(v, str)
    check inside the list branch silently skips tuples by design.
    """
    out: list[tuple[str, str]] = []
    for key, val in palette.items():
        kebab = _kebab(key)
        if isinstance(val, str):
            out.append((f"--{prefix}-{kebab}", val))
        elif isinstance(val, list):
            # delay_colors → --qs-delay-0, --qs-delay-1, ... (drop _colors suffix)
            stem = kebab.removesuffix("-colors") if kebab.endswith("-colors") else kebab
            for i, v in enumerate(val):
                if isinstance(v, str):
                    out.append((f"--{prefix}-{stem}-{i}", v))
        elif isinstance(val, dict):
            # model_colors → --qs-model-bub, --qs-model-qr, ...
            stem = kebab.removesuffix("-colors") if kebab.endswith("-colors") else kebab
            for k, v in val.items():
                if isinstance(v, str):
                    out.append((f"--{prefix}-{stem}-{_kebab(k)}", v))
        # tuple-of-tuple lists like thermal_stops are NOT exposed to CSS.
    return out


def _gather_top_level_constants() -> list[tuple[str, object]]:
    """Return [(name, value), ...] for every uppercase module-level
    constant in colors.py whose value is a str/dict/list and not in SKIP."""
    out = []
    for name in dir(colors):
        if not name.isupper():
            continue
        if name in SKIP:
            continue
        if name.startswith("_"):
            continue
        if name in ("PALETTE_KEYS",):
            continue
        val = getattr(colors, name)
        if isinstance(val, (str, dict, list)):
            out.append((name, val))
    return out


def _source_hash() -> str:
    """SHA256 of colors.py contents (first 16 hex chars)."""
    src = (_PROJECT_ROOT / "btc_web" / "colors.py").read_bytes()
    return hashlib.sha256(src).hexdigest()[:16]


def _generate_css() -> str:
    sha = _source_hash()
    lines = [
        f"/* AUTO-GENERATED by tools/generate_color_artifacts.py — DO NOT EDIT.",
        f"   Source: btc_web/colors.py  Source-SHA256: {sha} */",
        "",
        ":root {",
        "    /* ── Palette-invariant constants ── */",
    ]
    # Top-level scalar constants and dict-of-strings (e.g. CITADEL_OVERLAY_COLORS)
    for name, val in _gather_top_level_constants():
        if isinstance(val, str):
            lines.append(f"    --qs-{_kebab(name)}: {val};")
        elif isinstance(val, dict) and name not in ("DEFAULT", "CB_BRIAN", "CB_RG", "CB_FULL", "PALETTES"):
            # Flat dict-of-strings (TICKER_MODEL_COLORS, CITADEL_OVERLAY_COLORS, MODEL_TRACE_COLORS)
            stem = _kebab(name).removesuffix("-colors")
            for k, v in val.items():
                if isinstance(v, str):
                    lines.append(f"    --qs-{stem}-{_kebab(k)}: {v};")
    lines += [
        "",
        "    /* ── Default palette (active when no [data-palette] is set) ── */",
    ]
    for var_name, hex_val in _flatten_palette_for_css(colors.DEFAULT):
        lines.append(f"    {var_name}: {hex_val};")
    lines.append("}")
    lines.append("")
    # Per-palette overrides (skip default — it's already in :root)
    for pkey, pdict in colors.PALETTES.items():
        if pkey == "default":
            continue
        lines.append(f':root[data-palette="{pkey}"] {{')
        for var_name, hex_val in _flatten_palette_for_css(pdict):
            lines.append(f"    {var_name}: {hex_val};")
        lines.append("}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _js_repr(val) -> str:
    """JSON-ish JS literal for a Python value (str/list/tuple/dict)."""
    if isinstance(val, str):
        return f'"{val}"'
    if isinstance(val, (list, tuple)):
        return "[" + ", ".join(_js_repr(v) for v in val) + "]"
    if isinstance(val, dict):
        items = ", ".join(f'"{k}": {_js_repr(v)}' for k, v in val.items())
        return "{" + items + "}"
    return str(val)


def _generate_js() -> str:
    sha = _source_hash()
    lines = [
        f"/* AUTO-GENERATED by tools/generate_color_artifacts.py — DO NOT EDIT.",
        f"   Source: btc_web/colors.py  Source-SHA256: {sha} */",
        "(function() {",
        "    'use strict';",
        "    window.QS_COLORS = {",
    ]
    for name, val in _gather_top_level_constants():
        if isinstance(val, str):
            lines.append(f"        {name.lower()}: {_js_repr(val)},")
        elif isinstance(val, dict) and name not in ("DEFAULT", "CB_BRIAN", "CB_RG", "CB_FULL", "PALETTES"):
            lines.append(f"        {name.lower()}: {_js_repr(val)},")
    lines.append("    };")
    lines.append("    window.QS_PALETTES = {")
    for pkey, pdict in colors.PALETTES.items():
        lines.append(f'        "{pkey}": {_js_repr(pdict)},')
    lines.append("    };")
    # Spec-required dedicated namespace for ticker colors
    lines.append(f"    window.QS_TICKER_COLORS = {_js_repr(colors.TICKER_MODEL_COLORS)};")
    lines.append("})();")
    return "\n".join(lines) + "\n"


def write_artifacts() -> tuple[Path, Path]:
    css_text = _generate_css()
    js_text = _generate_js()
    CSS_PATH.write_text(css_text)
    JS_PATH.write_text(js_text)
    return CSS_PATH, JS_PATH


def check_artifacts() -> bool:
    """Return True if on-disk matches generated. False (and print diff hint) if not."""
    css_text = _generate_css()
    js_text = _generate_js()
    css_match = CSS_PATH.exists() and CSS_PATH.read_text() == css_text
    js_match = JS_PATH.exists() and JS_PATH.read_text() == js_text
    if not css_match:
        print(f"DRIFT: {CSS_PATH} differs from generated output", file=sys.stderr)
    if not js_match:
        print(f"DRIFT: {JS_PATH} differs from generated output", file=sys.stderr)
    return css_match and js_match


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 if on-disk artifacts differ from generated output")
    args = parser.parse_args()
    if args.check:
        ok = check_artifacts()
        sys.exit(0 if ok else 1)
    css_path, js_path = write_artifacts()
    print(f"Wrote {css_path}")
    print(f"Wrote {js_path}")


if __name__ == "__main__":
    main()
